#!/bin/sh

source /etc/os-release

if [ "$ID" == "arch" ]; then
    sudo pacman -S --needed base-devel
    
    # Install yay if needed
    if ! command -v paru $> /dev/null; then
        cd /tmp/
        git clone https://aur.archlinux.org/paru.git
        cd yay
        makepkg -sci --noconfirm
        cd ..
        rm yay -rf
    fi

    paru -S --needed --noconfirm - < ~/.config/yadm/pkglist
    paru -S --needed --noconfirm - < ~/.config/yadm/pkglist.host

	sudo chsh -s /bin/fish $USER

    git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/tpm
fi
